name: ci

on:
  push:
    branches:
      - "!main"
  pull_request:

  workflow_call:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: markdownlint
        run: make markdownlint
      - name: shell BDD tests
        run: make shelltest
      - name: prune
        run: make prune
