name: Lint

on:
  push:
    branches:
      - "!main"
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: markdownlint
        run: make markdownlint
      - name: prune
        run: make prune
