name: test-hooks

on:
  push:
  #   branches:
  #     - "!main"
  # pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test-implementation-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Test action step
        uses: ./ # Uses an action in the root directory
        env:
          MY_VAR: "bar"
        with:
          source_repo_path: AndreasAugustin/template.git
          upstream_branch: main
          is_dry_run: true
          is_allow_hooks: true
